
Level1 = [
        "PPPPPPPPPPPPPPPPPPPPPPPPP",
        "P                       P",
        "PPPPPPPPP  PPPP         P",
        "P       P               P",
        "P  P      P   PPPP      P",
        "P  PP     P   P         P",
        "P  PPP    PPP P    PPPPPP",
        "P  PPPP       P         P",
        "P  PPPPPP               P",
        "P  PPPPPPPPPP PPPPPPPPPPP",
        "P             PP        P",
        "P PP PP       PPP      PP",
        "P  PPPPPPPPPP PPPP    PPP",
        "P   P   P     PPPPP  PPPP",
        "P        PP   P         P",
        "P   PPP      PP         P",
        "P   PPPPPPPPPPP         P",
        "P               PPPPP   P",
        "P      PPPP   PPPPPPP   P",
        "PPPPPPPPPPPPPPPPPPPPPPPPP",
]

Level2 = [
        "PPPPPPPPPPPPPPPPPPPPPPPPP",
        "P                       P",
        "P  PPPPPP               P",
        "P  P     P    P         P",
        "P  P      P   P         P",
        "P  P       P  P         P",
        "P  P         PP    PPPPPP",
        "P  P        P P         P",
        "P  P       P  P         P",
        "P  P      P   PPPPPP    P",
        "P  P     P    PP        P",
        "P  P PP       PPP      PP",
        "P  PPPPP      PPPP    PPP",
        "P       P     PPPPP  PPPP",
        "P        PP   P         P",
        "P            PP         P",
        "P          PP P         P",
        "P       PP    P         P",
        "P      PPPP   PE        P",
        "PPPPPPPPPPPPPPPPPPPPPPPPP",
]

Level3 = [
        "PPPPPPPPPPPPPPPPPPPPPPPPP",
        "P  P                    P",
        "P  PPPPPP               P",
        "P  P     P    P         P",
        "P  P      P   P         P",
        "P  P       P  P         P",
        "P  P         PP    PPPPPP",
        "P  P        P P         P",
        "P  P       P  P         P",
        "P  P      P   PPPPPP    P",
        "P  P     P    PP        P",
        "P  P PP       PPP      PP",
        "P  PPPPP      PPPP    PPP",
        "P       P     PPPPP  PPPP",
        "P        PP   P         P",
        "P            PP         P",
        "P          PP P         P",
        "P       PP    P         P",
        "P      PPPP   PE        P",
        "PPPPPPPPPPPPPPPPPPPPPPPPP",
]